Тако што у падајућем менију промениш са "code" на "markdown".

In [3]:
import numpy as np
e1 = np.array([1, 0, 0])
e2 = np.array([0, 1, 0])
e3 = np.array([0, 0, 1])

In [4]:
e1 + e2

array([1, 1, 0])

In [5]:
e1 + e2 + e3

array([1, 1, 1])

In [6]:
e1 * e2

array([0, 0, 0])

In [7]:
e1 * e2 * e3

array([0, 0, 0])

**Скаларни производ два вектора**

In [8]:
np.dot(e1, e2)

0

In [9]:
np.dot(e1, e2.transpose())

0

**Интензитет вектора**

In [10]:
from numpy import linalg as lng

In [11]:
lng.norm(e1)

1.0

**Пројекција вектора**

In [17]:
a = np.array([4, 4, 0])
lng.norm(a)

5.656854249492381

In [18]:
(np.dot(a, e1)/np.dot(e1, e1))*e1

array([4., 0., 0.])

**Инверзна матрица**

In [12]:
A = np.array([[1, 2], [3, 4]])
lng.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

**Детерминанта матрице**

In [19]:
lng.det(A)

-2.0000000000000004

In [20]:
B = np.array([[3, 1], [6, 2]])
lng.det(B)

0.0

In [21]:
C = np.array([[1, 2], [-1, 4]])
D = np.array([[1, -1], [2, 4]])
np.dot(D, C)

array([[ 2, -2],
       [-2, 20]])

In [22]:
np.invert(D)

array([[-2,  0],
       [-3, -5]])

In [23]:
C = D

In [24]:
D = np.invert(D)

In [25]:
np.dot(C, D)

array([[  1,   5],
       [-16, -20]])